import { Link } from "react-router-dom";
import { FileText } from "lucide-react";
import { EmptyState } from "@/components/EmptyState";
import { ErrorState } from "@/components/ErrorState";
import { PageHeader } from "@/components/PageHeader";
import { RiskBadge } from "@/components/status-badges";
import { Card, CardContent } from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { useCurrentUser } from "@/hooks/useAuth";
import { useAdminQueue, useComplianceQueue } from "@/hooks/useSarReports";
import type { RiskLevel, SARReport } from "@/types/models";

function QueueTable({ items }: { items: SARReport[] }) {
  return (
    <Table>
      <TableHeader>
        <TableRow>
          <TableHead>Company</TableHead>
          <TableHead>Risk</TableHead>
          <TableHead>Recommendation</TableHead>
          <TableHead className="text-right">Generated</TableHead>
        </TableRow>
      </TableHeader>
      <TableBody>
        {items.map((sar) => (
          <TableRow key={sar.id} className="cursor-pointer">
            <TableCell className="font-medium text-foreground">
              <Link to={`/sar/${sar.id}`} className="block">
                {sar.company_name || sar.company_id}
              </Link>
            </TableCell>
            <TableCell>
              <RiskBadge level={(sar.company_risk_level ?? "unknown") as RiskLevel} />
            </TableCell>
            <TableCell className="max-w-xs truncate text-muted-foreground">
              {sar.review?.notes || "—"}
            </TableCell>
            <TableCell className="text-right text-muted-foreground">
              {new Date(sar.created_at).toLocaleDateString()}
            </TableCell>
          </TableRow>
        ))}
      </TableBody>
    </Table>
  );
}

export function SarReviewsPage() {
  const { data: currentUser, isLoading: isUserLoading } = useCurrentUser();
  const isAdmin = currentUser?.role === "ADMIN";

  // Only the query matching the resolved role is ever enabled — the other
  // endpoint 403s for this user, and firing it regardless would waste a
  // request that can only fail (see useComplianceQueue/useAdminQueue).
  const complianceQueue = useComplianceQueue(Boolean(currentUser) && !isAdmin);
  const adminQueue = useAdminQueue(Boolean(currentUser) && isAdmin);
  const { data, isLoading: isQueueLoading, isError, refetch } = isAdmin ? adminQueue : complianceQueue;

  const isLoading = isUserLoading || isQueueLoading;

  const title = isAdmin ? "Admin Deactivation Queue" : "Compliance Review Queue";
  const description = isAdmin
    ? "Deactivation recommendations from compliance officers awaiting your decision."
    : "SARs awaiting your review — recommend deactivation or reject with no further action.";

  return (
    <div className="space-y-6">
      <PageHeader title={title} description={description} />

      <Card>
        <CardContent className="px-0">
          {isLoading ? (
            <div className="space-y-3 px-4 py-2">
              {Array.from({ length: 6 }).map((_, i) => (
                <Skeleton key={i} className="h-9 w-full" />
              ))}
            </div>
          ) : isError ? (
            <ErrorState message="Could not load the review queue." onRetry={() => refetch()} />
          ) : !data || data.length === 0 ? (
            <EmptyState
              icon={FileText}
              title="Nothing waiting for review"
              description={
                isAdmin
                  ? "Recommendations approved by compliance officers will appear here."
                  : "SARs generated by the agent pipeline will appear here."
              }
            />
          ) : (
            <QueueTable items={data} />
          )}
        </CardContent>
      </Card>
    </div>
  );
}
